#
# Turns an episode into the matching schema.org object
#
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX po: <http://purl.org/ontology/po/>
PREFIX wdrs: <http://www.w3.org/2007/05/powder-s#>
PREFIX mrss: <http://search.yahoo.com/mrss/>

CONSTRUCT {
	?s rdf:type schema:Movie.
	?s rdfs:label ?label.
	?s rdfs:seeAlso ?credit.
	?s wdrs:describedBy ?player.
} WHERE {
	?s rdf:type po:Episode.
	?s rdfs:label ?label.
	?s po:contribution ?other.
	?s po:credit ?credit.
	?s mrss:player ?player.
}
